######################################################################
# Automatically generated by qmake (3.1) Thu Apr 17 19:32:34 2025
######################################################################

TEMPLATE = app
TARGET = SeniorProject2025
INCLUDEPATH += .

QT += widgets
QT += core
QT += gui 

CONFIG += c++17

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += arm_operators.h \
           branchAndSubroutines.h \
           calculations.h \
           constantsLabelsAndDataElements.h \
           directivesAndDataErrors.h \
           editwindow.h \
           Error.h \
           errorwindow.h \
           flags.h \
           main.h \
           mainwindow.h \
           pushPopErrors.h \
           ui_editwindow.h \
           ui_errorwindow.h \
           ui_mainwindow.h \
           CodeEditor.h
FORMS += editwindow.ui errorwindow.ui mainwindow.ui
SOURCES += branchAndSubroutines.cpp \
           calculations.cpp \
           constantsLabelsAndDataElements.cpp \
           directivesAndDataErrors.cpp \
           editwindow.cpp \
           Error.cpp \
           errorwindow.cpp \
           flags.cpp \
           main.cpp \
           mainwindow.cpp \
           pushPopErrors.cpp \
           CodeEditor.cpp
RESOURCES += SeniorProject2025.qrc
